// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNC3HQvHlWYIaGD6SdujsNedj1CdQLKts',
    appId: '1:626800146488:web:9e4bdcb989e92ba3d6cecd',
    messagingSenderId: '626800146488',
    projectId: 'unbounded-da560',
    authDomain: 'unbounded-da560.firebaseapp.com',
    storageBucket: 'unbounded-da560.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF1AgGmUdw7fVHRQUSYRaAmai5DF8pkQA',
    appId: '1:626800146488:android:1365b5053d9c3f9dd6cecd',
    messagingSenderId: '626800146488',
    projectId: 'unbounded-da560',
    storageBucket: 'unbounded-da560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjX9jQMXlUjoz69LtIBDwdpZAy2iFDk0g',
    appId: '1:626800146488:ios:48972f02c1d3fc65d6cecd',
    messagingSenderId: '626800146488',
    projectId: 'unbounded-da560',
    storageBucket: 'unbounded-da560.firebasestorage.app',
    iosBundleId: 'com.unbounded',
  );
}
